"""init schema

Revision ID: 5920e1a55b9d
Revises: 
Create Date: 2026-07-04 22:27:16.100412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5920e1a55b9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'draft', name='form_status'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_created_at'), 'forms', ['created_at'], unique=False)
    op.create_index(op.f('ix_forms_deleted'), 'forms', ['deleted'], unique=False)
    op.create_index(op.f('ix_forms_order'), 'forms', ['order'], unique=False)
    op.create_index(op.f('ix_forms_status'), 'forms', ['status'], unique=False)
    op.create_index(op.f('ix_forms_updated_at'), 'forms', ['updated_at'], unique=False)
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_created_at'), 'permissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_permissions_updated_at'), 'permissions', ['updated_at'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_created_at'), 'roles', ['created_at'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_updated_at'), 'roles', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='user_status'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table('fields',
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('text', 'number', 'date', 'color', 'select', name='field_type'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('validation_rules', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_created_at'), 'fields', ['created_at'], unique=False)
    op.create_index(op.f('ix_fields_form_id'), 'fields', ['form_id'], unique=False)
    op.create_index(op.f('ix_fields_updated_at'), 'fields', ['updated_at'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('submissions',
    sa.Column('form_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_by_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_created_at'), 'submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_submissions_form_id'), 'submissions', ['form_id'], unique=False)
    op.create_index(op.f('ix_submissions_submitted_by_id'), 'submissions', ['submitted_by_id'], unique=False)
    op.create_index(op.f('ix_submissions_updated_at'), 'submissions', ['updated_at'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('submission_answers',
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=True),
    sa.Column('field_label', sa.String(length=200), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_answers_created_at'), 'submission_answers', ['created_at'], unique=False)
    op.create_index(op.f('ix_submission_answers_field_id'), 'submission_answers', ['field_id'], unique=False)
    op.create_index(op.f('ix_submission_answers_submission_id'), 'submission_answers', ['submission_id'], unique=False)
    op.create_index(op.f('ix_submission_answers_updated_at'), 'submission_answers', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_answers_updated_at'), table_name='submission_answers')
    op.drop_index(op.f('ix_submission_answers_submission_id'), table_name='submission_answers')
    op.drop_index(op.f('ix_submission_answers_field_id'), table_name='submission_answers')
    op.drop_index(op.f('ix_submission_answers_created_at'), table_name='submission_answers')
    op.drop_table('submission_answers')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_submissions_updated_at'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_submitted_by_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_form_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_created_at'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_fields_updated_at'), table_name='fields')
    op.drop_index(op.f('ix_fields_form_id'), table_name='fields')
    op.drop_index(op.f('ix_fields_created_at'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_updated_at'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_created_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_updated_at'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_created_at'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_forms_updated_at'), table_name='forms')
    op.drop_index(op.f('ix_forms_status'), table_name='forms')
    op.drop_index(op.f('ix_forms_order'), table_name='forms')
    op.drop_index(op.f('ix_forms_deleted'), table_name='forms')
    op.drop_index(op.f('ix_forms_created_at'), table_name='forms')
    op.drop_table('forms')
    # ### end Alembic commands ###
